# Generated by Django 4.2.6 on 2023-10-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.CharField(default="", max_length=256),
        ),
    ]
